apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: {{ include "dummy-workflow.fullname" . }}-etcd
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "dummy-workflow.labels" . | indent 4 }}
spec:
  size: {{ .Values.etcd.replicas }}
  version: "{{ .Values.etcd.version }}"
  pod:
    antiAffinity: false
    nodeSelector: {}
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
