# Common definitions for GitLab CI files

# ============================================================================
# Common definitions for building Python packages
# ============================================================================

.build_python:
  stage: build
  image: python:latest
  artifacts:
    paths:
      - ./$BUILD_PATH/dist/
    expire_in: 1 week

# Executed on a non-master commit

.build_python_dev:
  extends: .build_python
  script:
    - cd $BUILD_PATH
    - python3 setup.py egg_info -b+dev.$CI_COMMIT_SHORT_SHA sdist bdist_wheel
  except: [master]

# Executed on a master commit

.build_python_release:
  extends: .build_python
  script:
    - cd $BUILD_PATH
    - python3 setup.py sdist bdist_wheel
  only: [master]

# ============================================================================
# Common definitions for publishing Python packages
# ============================================================================

.publish_python:
  stage: publish
  image: python:latest
  only: [master]
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  script:
    - python3 -m pip install twine
    - cd $BUILD_PATH
    - twine upload --repository-url $PYPI_REPOSITORY_URL dist/* || true
    - twine upload --skip-existing -u $PYPI_USER -p $PYPI_PASS dist/* || true

# ============================================================================
# Common definitions for testing Python packages
# ============================================================================

.test_python:
  stage: test
  image: nexus.engageska-portugal.pt/ska-docker/ska-python-buildenv:latest
  before_script:
    # Install from build artifacts
    - pip3 install ska-sdp-config --find-links src/config_db/dist
    - pip3 install ska-sdp-logging --find-links src/logging/dist
  script:
    - cd $BUILD_PATH
    - pip3 install -r requirements.txt -r requirements-test.txt
    - python3 setup.py test
  after_script:
    # Move the coverage and unit test reports to the top level
    - mv $BUILD_PATH/.coverage $CI_JOB_NAME.coverage
    - mv $BUILD_PATH/unit-tests.xml unit-tests-${CI_JOB_NAME}.xml
  artifacts:
    paths:
      - $CI_JOB_NAME.coverage
      - unit-tests-${CI_JOB_NAME}.xml
    expire_in: 1 week
    when: always

.test_with_etcd:
  services:
    - name: quay.io/coreos/etcd:latest
      alias: etcd
      command:
        - /usr/local/bin/etcd
        - "--advertise-client-urls=http://0.0.0.0:2379"
        - "--listen-client-urls=http://0.0.0.0:2379"
        - "--initial-advertise-peer-urls=http://0.0.0.0:2380"
        - "--listen-peer-urls=http://0.0.0.0:2380"
        - "--initial-cluster=default=http://0.0.0.0:2380"

# ============================================================================
# Common definitions for building Docker images
# ============================================================================

.build_docker:
  stage: build_docker
  dependencies:
    - build:ska-sdp-logging_dev
    - build:ska-sdp-config_dev
    - build:ska-sdp-logging
    - build:ska-sdp-config
  variables:
    GIT_VERSION: ${CI_COMMIT_SHORT_SHA}
    PREFIX_BUILD: ${CI_REGISTRY_IMAGE}
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add make git
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cp src/config_db/dist/*.whl $BUILD_PATH
    - cp src/logging/dist/*.whl $BUILD_PATH
    - cd $BUILD_PATH
    - make build
    - make push

# ============================================================================
# Common definitions for publishing Docker images
# ============================================================================

.publish_docker:
  stage: publish
  only: [master]
  variables:
    GIT_VERSION: ${CI_COMMIT_SHORT_SHA}
    PREFIX_BUILD: ${CI_REGISTRY_IMAGE}
    PREFIX_RELEASE: ${DOCKER_REGISTRY_HOST}/${CI_PROJECT_NAME}
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apk add make git
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_HOST
  script:
    - cd $BUILD_PATH
    - make pull
    - make push_release
  retry: 2

# ============================================================================
# Common definitions for uploading results of XRay tests
# ============================================================================

.xray_report:
  stage: publish
  only: [master]
  when: always
  allow_failure: true
  image: python:latest
  script:
    - 'curl -X POST -H "Content-Type: application/json" --fail
         -H "Authorization: Basic $JIRA_AUTH"
         --data @cucumber.json
         https://jira.skatelescope.org/rest/raven/1.0/import/execution/cucumber'
  retry: 2 # In case JIRA doesn't work first time
